import { createRandomOneNine } from "./generator.ts";
import type { Address, Cell, Puzzle } from "../client/src/types.d.ts";

export class BlankCell implements Cell {
  number = ".";
  given = false;
  pencilMarks = [false, false, false, false, false, false, false, false, false];
  valid = true;
  candidates = [];
  address:Address;
  untriedNumbers = createRandomOneNine();
  constructor(address: Address) {
    this.address = address;
  }
}

export class BlankPuzzle implements Puzzle {
  [index: string]: Cell;
  r1c1: Cell = new BlankCell({ r: 1, c: 1 });
  r1c2: Cell = new BlankCell({ r: 1, c: 2 });
  r1c3: Cell = new BlankCell({ r: 1, c: 3 });
  r1c4: Cell = new BlankCell({ r: 1, c: 4 });
  r1c5: Cell = new BlankCell({ r: 1, c: 5 });
  r1c6: Cell = new BlankCell({ r: 1, c: 6 });
  r1c7: Cell = new BlankCell({ r: 1, c: 7 });
  r1c8: Cell = new BlankCell({ r: 1, c: 8 });
  r1c9: Cell = new BlankCell({ r: 1, c: 9 });
  r2c1: Cell = new BlankCell({ r: 2, c: 1 });
  r2c2: Cell = new BlankCell({ r: 2, c: 2 });
  r2c3: Cell = new BlankCell({ r: 2, c: 3 });
  r2c4: Cell = new BlankCell({ r: 2, c: 4 });
  r2c5: Cell = new BlankCell({ r: 2, c: 5 });
  r2c6: Cell = new BlankCell({ r: 2, c: 6 });
  r2c7: Cell = new BlankCell({ r: 2, c: 7 });
  r2c8: Cell = new BlankCell({ r: 2, c: 8 });
  r2c9: Cell = new BlankCell({ r: 2, c: 9 });
  r3c1: Cell = new BlankCell({ r: 3, c: 1 });
  r3c2: Cell = new BlankCell({ r: 3, c: 2 });
  r3c3: Cell = new BlankCell({ r: 3, c: 3 });
  r3c4: Cell = new BlankCell({ r: 3, c: 4 });
  r3c5: Cell = new BlankCell({ r: 3, c: 5 });
  r3c6: Cell = new BlankCell({ r: 3, c: 6 });
  r3c7: Cell = new BlankCell({ r: 3, c: 7 });
  r3c8: Cell = new BlankCell({ r: 3, c: 8 });
  r3c9: Cell = new BlankCell({ r: 3, c: 9 });
  r4c1: Cell = new BlankCell({ r: 4, c: 1 });
  r4c2: Cell = new BlankCell({ r: 4, c: 2 });
  r4c3: Cell = new BlankCell({ r: 4, c: 3 });
  r4c4: Cell = new BlankCell({ r: 4, c: 4 });
  r4c5: Cell = new BlankCell({ r: 4, c: 5 });
  r4c6: Cell = new BlankCell({ r: 4, c: 6 });
  r4c7: Cell = new BlankCell({ r: 4, c: 7 });
  r4c8: Cell = new BlankCell({ r: 4, c: 8 });
  r4c9: Cell = new BlankCell({ r: 4, c: 9 });
  r5c1: Cell = new BlankCell({ r: 5, c: 1 });
  r5c2: Cell = new BlankCell({ r: 5, c: 2 });
  r5c3: Cell = new BlankCell({ r: 5, c: 3 });
  r5c4: Cell = new BlankCell({ r: 5, c: 4 });
  r5c5: Cell = new BlankCell({ r: 5, c: 5 });
  r5c6: Cell = new BlankCell({ r: 5, c: 6 });
  r5c7: Cell = new BlankCell({ r: 5, c: 7 });
  r5c8: Cell = new BlankCell({ r: 5, c: 8 });
  r5c9: Cell = new BlankCell({ r: 5, c: 9 });
  r6c1: Cell = new BlankCell({ r: 6, c: 1 });
  r6c2: Cell = new BlankCell({ r: 6, c: 2 });
  r6c3: Cell = new BlankCell({ r: 6, c: 3 });
  r6c4: Cell = new BlankCell({ r: 6, c: 4 });
  r6c5: Cell = new BlankCell({ r: 6, c: 5 });
  r6c6: Cell = new BlankCell({ r: 6, c: 6 });
  r6c7: Cell = new BlankCell({ r: 6, c: 7 });
  r6c8: Cell = new BlankCell({ r: 6, c: 8 });
  r6c9: Cell = new BlankCell({ r: 6, c: 9 });
  r7c1: Cell = new BlankCell({ r: 7, c: 1 });
  r7c2: Cell = new BlankCell({ r: 7, c: 2 });
  r7c3: Cell = new BlankCell({ r: 7, c: 3 });
  r7c4: Cell = new BlankCell({ r: 7, c: 4 });
  r7c5: Cell = new BlankCell({ r: 7, c: 5 });
  r7c6: Cell = new BlankCell({ r: 7, c: 6 });
  r7c7: Cell = new BlankCell({ r: 7, c: 7 });
  r7c8: Cell = new BlankCell({ r: 7, c: 8 });
  r7c9: Cell = new BlankCell({ r: 7, c: 9 });
  r8c1: Cell = new BlankCell({ r: 8, c: 1 });
  r8c2: Cell = new BlankCell({ r: 8, c: 2 });
  r8c3: Cell = new BlankCell({ r: 8, c: 3 });
  r8c4: Cell = new BlankCell({ r: 8, c: 4 });
  r8c5: Cell = new BlankCell({ r: 8, c: 5 });
  r8c6: Cell = new BlankCell({ r: 8, c: 6 });
  r8c7: Cell = new BlankCell({ r: 8, c: 7 });
  r8c8: Cell = new BlankCell({ r: 8, c: 8 });
  r8c9: Cell = new BlankCell({ r: 8, c: 9 });
  r9c1: Cell = new BlankCell({ r: 9, c: 1 });
  r9c2: Cell = new BlankCell({ r: 9, c: 2 });
  r9c3: Cell = new BlankCell({ r: 9, c: 3 });
  r9c4: Cell = new BlankCell({ r: 9, c: 4 });
  r9c5: Cell = new BlankCell({ r: 9, c: 5 });
  r9c6: Cell = new BlankCell({ r: 9, c: 6 });
  r9c7: Cell = new BlankCell({ r: 9, c: 7 });
  r9c8: Cell = new BlankCell({ r: 9, c: 8 });
  r9c9: Cell = new BlankCell({ r: 9, c: 9 });
}
