import { createRandomOneNine } from "./generator.ts"
import { Cell, Puzzle } from "../client/src/types.d.ts"
export default class BlankPuzzle implements Puzzle {
    [index: string]: Cell;
    r1c1: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 1, c: 1 },
        untriedNumbers: createRandomOneNine(),
    };
    r1c2: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 1, c: 2 },
        untriedNumbers: createRandomOneNine(),
    };
    r1c3: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 1, c: 3 },
        untriedNumbers: createRandomOneNine(),
    };
    r1c4: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 1, c: 4 },
        untriedNumbers: createRandomOneNine(),
    };
    r1c5: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 1, c: 5 },
        untriedNumbers: createRandomOneNine(),
    };
    r1c6: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 1, c: 6 },
        untriedNumbers: createRandomOneNine(),
    };
    r1c7: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 1, c: 7 },
        untriedNumbers: createRandomOneNine(),
    };
    r1c8: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 1, c: 8 },
        untriedNumbers: createRandomOneNine(),
    };
    r1c9: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 1, c: 9 },
        untriedNumbers: createRandomOneNine(),
    };
    r2c1: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 2, c: 1 },
        untriedNumbers: createRandomOneNine(),
    };
    r2c2: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 2, c: 2 },
        untriedNumbers: createRandomOneNine(),
    };
    r2c3: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 2, c: 3 },
        untriedNumbers: createRandomOneNine(),
    };
    r2c4: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 2, c: 4 },
        untriedNumbers: createRandomOneNine(),
    };
    r2c5: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 2, c: 5 },
        untriedNumbers: createRandomOneNine(),
    };
    r2c6: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 2, c: 6 },
        untriedNumbers: createRandomOneNine(),
    };
    r2c7: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 2, c: 7 },
        untriedNumbers: createRandomOneNine(),
    };
    r2c8: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 2, c: 8 },
        untriedNumbers: createRandomOneNine(),
    };
    r2c9: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 2, c: 9 },
        untriedNumbers: createRandomOneNine(),
    };
    r3c1: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 3, c: 1 },
        untriedNumbers: createRandomOneNine(),
    };
    r3c2: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 3, c: 2 },
        untriedNumbers: createRandomOneNine(),
    };
    r3c3: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 3, c: 3 },
        untriedNumbers: createRandomOneNine(),
    };
    r3c4: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 3, c: 4 },
        untriedNumbers: createRandomOneNine(),
    };
    r3c5: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 3, c: 5 },
        untriedNumbers: createRandomOneNine(),
    };
    r3c6: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 3, c: 6 },
        untriedNumbers: createRandomOneNine(),
    };
    r3c7: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 3, c: 7 },
        untriedNumbers: createRandomOneNine(),
    };
    r3c8: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 3, c: 8 },
        untriedNumbers: createRandomOneNine(),
    };
    r3c9: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 3, c: 9 },
        untriedNumbers: createRandomOneNine(),
    };
    r4c1: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 4, c: 1 },
        untriedNumbers: createRandomOneNine(),
    };
    r4c2: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 4, c: 2 },
        untriedNumbers: createRandomOneNine(),
    };
    r4c3: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 4, c: 3 },
        untriedNumbers: createRandomOneNine(),
    };
    r4c4: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 4, c: 4 },
        untriedNumbers: createRandomOneNine(),
    };
    r4c5: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 4, c: 5 },
        untriedNumbers: createRandomOneNine(),
    };
    r4c6: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 4, c: 6 },
        untriedNumbers: createRandomOneNine(),
    };
    r4c7: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 4, c: 7 },
        untriedNumbers: createRandomOneNine(),
    };
    r4c8: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 4, c: 8 },
        untriedNumbers: createRandomOneNine(),
    };
    r4c9: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 4, c: 9 },
        untriedNumbers: createRandomOneNine(),
    };
    r5c1: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 5, c: 1 },
        untriedNumbers: createRandomOneNine(),
    };
    r5c2: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 5, c: 2 },
        untriedNumbers: createRandomOneNine(),
    };
    r5c3: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 5, c: 3 },
        untriedNumbers: createRandomOneNine(),
    };
    r5c4: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 5, c: 4 },
        untriedNumbers: createRandomOneNine(),
    };
    r5c5: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 5, c: 5 },
        untriedNumbers: createRandomOneNine(),
    };
    r5c6: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 5, c: 6 },
        untriedNumbers: createRandomOneNine(),
    };
    r5c7: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 5, c: 7 },
        untriedNumbers: createRandomOneNine(),
    };
    r5c8: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 5, c: 8 },
        untriedNumbers: createRandomOneNine(),
    };
    r5c9: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 5, c: 9 },
        untriedNumbers: createRandomOneNine(),
    };
    r6c1: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 6, c: 1 },
        untriedNumbers: createRandomOneNine(),
    };
    r6c2: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 6, c: 2 },
        untriedNumbers: createRandomOneNine(),
    };
    r6c3: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 6, c: 3 },
        untriedNumbers: createRandomOneNine(),
    };
    r6c4: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 6, c: 4 },
        untriedNumbers: createRandomOneNine(),
    };
    r6c5: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 6, c: 5 },
        untriedNumbers: createRandomOneNine(),
    };
    r6c6: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 6, c: 6 },
        untriedNumbers: createRandomOneNine(),
    };
    r6c7: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 6, c: 7 },
        untriedNumbers: createRandomOneNine(),
    };
    r6c8: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 6, c: 8 },
        untriedNumbers: createRandomOneNine(),
    };
    r6c9: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 6, c: 9 },
        untriedNumbers: createRandomOneNine(),
    };
    r7c1: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 7, c: 1 },
        untriedNumbers: createRandomOneNine(),
    };
    r7c2: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 7, c: 2 },
        untriedNumbers: createRandomOneNine(),
    };
    r7c3: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 7, c: 3 },
        untriedNumbers: createRandomOneNine(),
    };
    r7c4: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 7, c: 4 },
        untriedNumbers: createRandomOneNine(),
    };
    r7c5: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 7, c: 5 },
        untriedNumbers: createRandomOneNine(),
    };
    r7c6: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 7, c: 6 },
        untriedNumbers: createRandomOneNine(),
    };
    r7c7: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 7, c: 7 },
        untriedNumbers: createRandomOneNine(),
    };
    r7c8: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 7, c: 8 },
        untriedNumbers: createRandomOneNine(),
    };
    r7c9: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 7, c: 9 },
        untriedNumbers: createRandomOneNine(),
    };
    r8c1: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 8, c: 1 },
        untriedNumbers: createRandomOneNine(),
    };
    r8c2: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 8, c: 2 },
        untriedNumbers: createRandomOneNine(),
    };
    r8c3: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 8, c: 3 },
        untriedNumbers: createRandomOneNine(),
    };
    r8c4: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 8, c: 4 },
        untriedNumbers: createRandomOneNine(),
    };
    r8c5: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 8, c: 5 },
        untriedNumbers: createRandomOneNine(),
    };
    r8c6: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 8, c: 6 },
        untriedNumbers: createRandomOneNine(),
    };
    r8c7: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 8, c: 7 },
        untriedNumbers: createRandomOneNine(),
    };
    r8c8: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 8, c: 8 },
        untriedNumbers: createRandomOneNine(),
    };
    r8c9: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 8, c: 9 },
        untriedNumbers: createRandomOneNine(),
    };
    r9c1: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 9, c: 1 },
        untriedNumbers: createRandomOneNine(),
    };
    r9c2: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 9, c: 2 },
        untriedNumbers: createRandomOneNine(),
    };
    r9c3: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 9, c: 3 },
        untriedNumbers: createRandomOneNine(),
    };
    r9c4: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 9, c: 4 },
        untriedNumbers: createRandomOneNine(),
    };
    r9c5: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 9, c: 5 },
        untriedNumbers: createRandomOneNine(),
    };
    r9c6: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 9, c: 6 },
        untriedNumbers: createRandomOneNine(),
    };
    r9c7: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 9, c: 7 },
        untriedNumbers: createRandomOneNine(),
    };
    r9c8: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 9, c: 8 },
        untriedNumbers: createRandomOneNine(),
    };
    r9c9: Cell = {
        number: ".",
        given: false,
        pencilMarks: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ],
        valid: true,
        candidates: [],
        address: { r: 9, c: 9 },
        untriedNumbers: createRandomOneNine(),
    };
}